name: Render video
on:
  workflow_dispatch:
    inputs:
      titleText:
        description: "Which text should it say?"
        required: true
        default: "Welcome to Remotion"
      titleColor:
        description: "Which color should it be in?"
        required: true
        default: "black"
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Node.JS environment
        uses: actions/setup-node@main

      - name: Install FFMPEG
        run: sudo apt update
        run: sudo apt install ffmpeg
      - run: yarn
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
        
      - name: Create Youtube video
        run: yarn remotion render HelloWorld out/video.mp4 --props="./input-props.json"
      #  run: ./bin/run create youtube --upload

      #- run: npm run build -- --props="./input-props.json"

      - name: Save video in Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out/video.mp4